// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "C:/Users/jaime_m7f43jl/root-on-vscode/hsimple.C";

#endif
